openapi: 3.2.0
info:
  title: DNSFilter Domains API
  description: '**Note:** If you are a distributor integrating with DNSFilter, please check

    out our Distributors Development Guide.'
  version: '2026-07-13'
servers:
- url: https://api.dnsfilter.com
  description: Production
tags:
- name: Domains
  description: ''
paths:
  /v1/domains/user_lookup:
    get:
      tags:
      - Domains
      operationId: V1_Domains-user_lookup
      parameters:
      - name: fqdn
        description: FQDN to lookup
        required: false
        in: query
        schema:
          type: string
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '200':
          description: Domains basic information
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/DomainSpec'
      description: Gets all the domains associated for a particular FQDN.
      summary: Lookup
      security:
      - header_authorization: []
      x-controller: v1/domains
      x-action: user_lookup
  /v1/domains/bulk_lookup:
    get:
      tags:
      - Domains
      operationId: V1_Domains-bulk_lookup
      parameters:
      - name: fqdns
        description: Comma separated list of FQDNs to lookup
        required: false
        in: query
        schema:
          type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '200':
          description: Domains basic information
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DomainSpec'
      description: Gets the domains and categories associated for each FQDN of the specified list.
      summary: Bulk lookup
      security:
      - header_authorization: []
      x-controller: v1/domains
      x-action: bulk_lookup
  /v1/domains/suggest_threat:
    post:
      tags:
      - Domains
      operationId: V1_Domains-suggest_threat
      parameters:
      - name: categories
        description: Suggested security categories, comma separated IDs
        required: false
        in: query
        schema:
          type: string
      - name: fqdn
        description: FQDN to verify
        required: true
        in: query
        schema:
          type: string
      - name: notes
        description: User notes about the threat suggestion/verification
        required: true
        in: query
        schema:
          type: string
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '200':
          description: Operation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
      description: 'Mark a FQDN to verify its threat categorization.


        Request example: `/v1/domains/suggest_threat?fqdn=XXXX¬es&test-report&categories=1,222,989`'
      summary: Suggest threat
      security:
      - header_authorization: []
      x-controller: v1/domains
      x-action: suggest_threat
components:
  schemas:
    IdType:
      type: object
      properties:
        id:
          type: string
          description: Resource Id (integer or uuid)
        type:
          type: string
          description: Resource type name
        uuid:
          type: string
          description: Resource UUID (if applicable)
      description: JSON API resource ID and type attributes
    DomainSpec:
      allOf:
      - $ref: '#/components/schemas/IdType'
      - $ref: '#/components/schemas/ApplicationLookup'
      - type: object
        properties:
          attributes:
            $ref: '#/components/schemas/Domain'
          relationships:
            type: object
            properties:
              categories:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/IdType'
            description: Domain current associated categories and applications
      description: Domain specification
    Domain:
      type: object
      properties:
        host:
          type: string
          description: Host
        name:
          type: string
          description: Name
      description: Domain resource
    Success:
      type: object
      properties:
        success:
          type: boolean
          description: Successful operation yes/no
      description: Success basic representation
    Error:
      type: object
      properties:
        error:
          type: string
          description: 'Error message (e.x.: Not Authorized)'
      description: Error basic representation
    ApplicationLookup:
      type: object
      properties:
        id:
          type: integer
          description: Application Id
        name:
          type: string
          description: Application name
        category:
          type: string
          description: Application category name
      description: ApplicationLookup resource
  securitySchemes:
    header_authorization:
      type: apiKey
      name: Authorization
      in: header
